[build]
  base = "fronted"
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NODE_VERSION = "18"
  VITE_API_URL = "https://tfg-portafolios-production.up.railway.app"

[context.deploy-preview.environment]
  NODE_VERSION = "18"
  VITE_API_URL = "https://tfg-portafolios-production.up.railway.app"

[context.branch-deploy.environment]
  NODE_VERSION = "18"
  VITE_API_URL = "https://tfg-portafolios-production.up.railway.app"
